<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NZJM51vService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.nZJM51v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nZJM51v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeEntiteRepository' => ['privates', 'App\\Repository\\TypeEntiteRepository', 'getTypeEntiteRepositoryService', true],
        ], [
            'typeEntiteRepository' => 'App\\Repository\\TypeEntiteRepository',
        ]);
    }
}
