<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I4rbcsKService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.i4rbcsK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i4rbcsK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', '.errored.ux9e4lA', NULL, 'Cannot determine controller argument for "App\\Controller\\Users\\ProfilController::index()": the $fileUploader argument is type-hinted with the non-existent class or interface: "App\\Service\\Api\\FileUploader".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'fileUploader' => '?',
            'manager' => '?',
        ]);
    }
}
