<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Ux9e4lAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.ux9e4lA' shared service.
     *
     * @return \App\Service\Api\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Users\\ProfilController::index()": the $fileUploader argument is type-hinted with the non-existent class or interface: "App\\Service\\Api\\FileUploader".');
    }
}
