<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OkGysMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored._okGysM' shared service.
     *
     * @return \App\Controller\Articles\LivreOldRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Articles\\ArticleController::transfertBDDLivre()": the $livreOldRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\Articles\\LivreOldRepository". Did you forget to add a use statement?');
    }
}
