<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ma4znPtService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ma4znPt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ma4znPt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.Ma4znPt.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.Ma4znPt": it references class "App\\Entity\\Article" but no such service exists.'],
            'statutRepository' => ['privates', 'App\\Repository\\StatutRepository', 'getStatutRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'statutRepository' => 'App\\Repository\\StatutRepository',
        ]);
    }
}
