<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXifZ5TService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xXifZ5T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xXifZ5T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actionsRepo' => ['privates', 'App\\Repository\\ActionRepository', 'getActionRepositoryService', true],
            'ar' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'filtre' => ['privates', 'App\\Service\\Article\\Filtre', 'getFiltreService', true],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'new' => ['privates', 'App\\Service\\Article\\Nouveaute', 'getNouveauteService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'actionsRepo' => 'App\\Repository\\ActionRepository',
            'ar' => 'App\\Repository\\ArticleRepository',
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
            'filtre' => 'App\\Service\\Article\\Filtre',
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'new' => 'App\\Service\\Article\\Nouveaute',
            'paginator' => '?',
            'session' => '?',
        ]);
    }
}
