<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8oZzKapService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8oZzKap' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8oZzKap'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fonctionRepository' => ['privates', 'App\\Repository\\FonctionRepository', 'getFonctionRepositoryService', true],
        ], [
            'fonctionRepository' => 'App\\Repository\\FonctionRepository',
        ]);
    }
}
