<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZtH5vmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zt_H5vm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zt_H5vm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actionsRepo' => ['privates', 'App\\Repository\\ActionRepository', 'getActionRepositoryService', true],
            'ar' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'new' => ['privates', 'App\\Service\\Article\\Nouveaute', 'getNouveauteService', true],
        ], [
            'actionsRepo' => 'App\\Repository\\ActionRepository',
            'ar' => 'App\\Repository\\AnnonceRepository',
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
            'new' => 'App\\Service\\Article\\Nouveaute',
        ]);
    }
}
