<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AyAB88Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AyAB88_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AyAB88_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ar' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'enregistrementRepository' => ['privates', 'App\\Repository\\EnregistrementRepository', 'getEnregistrementRepositoryService', true],
            'filtre' => ['privates', 'App\\Service\\Article\\Filtre', 'getFiltreService', true],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'ar' => 'App\\Repository\\ArticleRepository',
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
            'enregistrementRepository' => 'App\\Repository\\EnregistrementRepository',
            'filtre' => 'App\\Service\\Article\\Filtre',
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'paginator' => '?',
            'session' => '?',
        ]);
    }
}
