<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AvisFormType' shared autowired service.
     *
     * @return \App\Form\AvisFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AvisFormType'] = new \App\Form\AvisFormType();
    }
}
