<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvatarProfilFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AvatarProfilFormType' shared autowired service.
     *
     * @return \App\Form\AvatarProfilFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AvatarProfilFormType'] = new \App\Form\AvatarProfilFormType();
    }
}
