<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBibliothequeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BibliothequeRepository' shared autowired service.
     *
     * @return \App\Repository\BibliothequeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BibliothequeRepository'] = new \App\Repository\BibliothequeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
