<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.57pSehj.App\Entity\Categorie' shared service.
     *
     * @return \App\Entity\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.57pSehj": it references class "App\\Entity\\Categorie" but no such service exists.');
    }
}
