<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrepriseService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ggm84RA.App\Entity\Entreprise' shared service.
     *
     * @return \App\Entity\Entreprise
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ggm84RA": it references class "App\\Entity\\Entreprise" but no such service exists.');
    }
}
