<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntiteTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EntiteType' shared autowired service.
     *
     * @return \App\Form\EntiteType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EntiteType'] = new \App\Form\EntiteType();
    }
}
