<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntiteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mHBSyR7.App\Entity\Entite' shared service.
     *
     * @return \App\Entity\Entite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mHBSyR7": it references class "App\\Entity\\Entite" but no such service exists.');
    }
}
