<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFonctionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FonctionType' shared autowired service.
     *
     * @return \App\Form\FonctionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FonctionType'] = new \App\Form\FonctionType();
    }
}
