<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFonctionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.VK74fLD.App\Entity\Fonction' shared service.
     *
     * @return \App\Entity\Fonction
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VK74fLD": it references class "App\\Entity\\Fonction" but no such service exists.');
    }
}
