<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.6aw_DHk.App\Entity\Genre' shared service.
     *
     * @return \App\Entity\Genre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6aw_DHk": it references class "App\\Entity\\Genre" but no such service exists.');
    }
}
