<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreApiService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Api\LivreApi' shared autowired service.
     *
     * @return \App\Service\Api\LivreApi
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Api\\LivreApi'] = new \App\Service\Api\LivreApi(($container->services['serializer'] ?? $container->load('getSerializerService')));
    }
}
