<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Users\ProfilController' shared autowired service.
     *
     * @return \App\Controller\Users\ProfilController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Users\\ProfilController'] = $instance = new \App\Controller\Users\ProfilController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Users\\ProfilController', $container));

        return $instance;
    }
}
