<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRubriqueService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.UuZjYyu.App\Entity\Rubrique' shared service.
     *
     * @return \App\Entity\Rubrique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UuZjYyu": it references class "App\\Entity\\Rubrique" but no such service exists.');
    }
}
