<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutEnregistrementRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StatutEnregistrementRepository' shared autowired service.
     *
     * @return \App\Repository\StatutEnregistrementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StatutEnregistrementRepository'] = new \App\Repository\StatutEnregistrementRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
