<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrancheAgeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\TrancheAgeController' shared autowired service.
     *
     * @return \App\Controller\TrancheAgeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\TrancheAgeController'] = $instance = new \App\Controller\TrancheAgeController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\TrancheAgeController', $container));

        return $instance;
    }
}
