<?php

namespace ContainerDDUIVed;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEntiteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.DfW_9E0.App\Entity\TypeEntite' shared service.
     *
     * @return \App\Entity\TypeEntite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DfW_9E0": it references class "App\\Entity\\TypeEntite" but no such service exists.');
    }
}
