<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Videold extends \App\Entity\Videold implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeTheque', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeArticle', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'gencode', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'nomAuteur', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'prenomAuteur', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'support', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateAchat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'prixAchat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'sortie', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'nbSortie', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'tag', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeEtat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateRetrait', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateCreation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeTheque', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeArticle', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'gencode', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'nomAuteur', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'prenomAuteur', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'support', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateAchat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'prixAchat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'sortie', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'nbSortie', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'tag', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'codeEtat', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateRetrait', '' . "\0" . 'App\\Entity\\Videold' . "\0" . 'dateCreation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Videold $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeTheque(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeTheque', []);

        return parent::getCodeTheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeTheque(?string $codeTheque): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeTheque', [$codeTheque]);

        return parent::setCodeTheque($codeTheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeArticle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeArticle', []);

        return parent::getCodeArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeArticle(string $codeArticle): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeArticle', [$codeArticle]);

        return parent::setCodeArticle($codeArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getGencode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGencode', []);

        return parent::getGencode();
    }

    /**
     * {@inheritDoc}
     */
    public function setGencode(?string $gencode): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGencode', [$gencode]);

        return parent::setGencode($gencode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(?string $titre): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomAuteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomAuteur', []);

        return parent::getNomAuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomAuteur(?string $nomAuteur): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomAuteur', [$nomAuteur]);

        return parent::setNomAuteur($nomAuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomAuteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomAuteur', []);

        return parent::getPrenomAuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomAuteur(?string $prenomAuteur): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomAuteur', [$prenomAuteur]);

        return parent::setPrenomAuteur($prenomAuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupport(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupport', []);

        return parent::getSupport();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupport(?string $support): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupport', [$support]);

        return parent::setSupport($support);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAchat(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAchat', []);

        return parent::getDateAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAchat(?\DateTimeInterface $dateAchat): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAchat', [$dateAchat]);

        return parent::setDateAchat($dateAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixAchat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixAchat', []);

        return parent::getPrixAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixAchat(?string $prixAchat): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixAchat', [$prixAchat]);

        return parent::setPrixAchat($prixAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortie', []);

        return parent::getSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortie(?string $sortie): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortie', [$sortie]);

        return parent::setSortie($sortie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', []);

        return parent::getTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag(?string $tag): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag', [$tag]);

        return parent::setTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeEtat', []);

        return parent::getCodeEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeEtat(?string $codeEtat): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeEtat', [$codeEtat]);

        return parent::setCodeEtat($codeEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRetrait(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRetrait', []);

        return parent::getDateRetrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRetrait(?\DateTimeInterface $dateRetrait): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRetrait', [$dateRetrait]);

        return parent::setDateRetrait($dateRetrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(?\DateTimeInterface $dateCreation): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSortie(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSortie', []);

        return parent::getNbSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSortie(?int $nbSortie): \App\Entity\Videold
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSortie', [$nbSortie]);

        return parent::setNbSortie($nbSortie);
    }

}
