<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOiS04YC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOiS04YC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOiS04YC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOiS04YC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOiS04YC\App_KernelDevDebugContainer([
    'container.build_hash' => 'OiS04YC',
    'container.build_id' => '1e78fc09',
    'container.build_time' => 1612133514,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOiS04YC');
