<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLeAqLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._DLeAqL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._DLeAqL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'enregistrementRepository' => ['privates', 'App\\Repository\\EnregistrementRepository', 'getEnregistrementRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'enregistrementRepository' => 'App\\Repository\\EnregistrementRepository',
            'paginator' => '?',
        ]);
    }
}
