<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DNvNaxOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DNvNaxO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DNvNaxO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livreApi' => ['privates', 'App\\Service\\Api\\LivreApi', 'getLivreApiService', true],
        ], [
            'livreApi' => 'App\\Service\\Api\\LivreApi',
        ]);
    }
}
