<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wx7tQuiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wx7tQui' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wx7tQui'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lien' => ['privates', '.errored..service_locator.Wx7tQui.App\\Entity\\Lien', NULL, 'Cannot autowire service ".service_locator.Wx7tQui": it references class "App\\Entity\\Lien" but no such service exists.'],
        ], [
            'lien' => 'App\\Entity\\Lien',
        ]);
    }
}
