<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DfW9E0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DfW_9E0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DfW_9E0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeEntite' => ['privates', '.errored..service_locator.DfW_9E0.App\\Entity\\TypeEntite', NULL, 'Cannot autowire service ".service_locator.DfW_9E0": it references class "App\\Entity\\TypeEntite" but no such service exists.'],
        ], [
            'typeEntite' => 'App\\Entity\\TypeEntite',
        ]);
    }
}
