<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ewosi97Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ewosi97' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ewosi97'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'typeEnregistrementRepository' => ['privates', 'App\\Repository\\TypeEnregistrementRepository', 'getTypeEnregistrementRepositoryService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'panierRepository' => 'App\\Repository\\PanierRepository',
            'typeEnregistrementRepository' => 'App\\Repository\\TypeEnregistrementRepository',
        ]);
    }
}
