<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiltreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Article\Filtre' shared autowired service.
     *
     * @return \App\Service\Article\Filtre
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Article/Filtre.php';

        return $container->privates['App\\Service\\Article\\Filtre'] = new \App\Service\Article\Filtre();
    }
}
