<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLienService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Wx7tQui.App\Entity\Lien' shared service.
     *
     * @return \App\Entity\Lien
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Wx7tQui": it references class "App\\Entity\\Lien" but no such service exists.');
    }
}
