<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrancheAgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kkPDExG.App\Entity\TrancheAge' shared service.
     *
     * @return \App\Entity\TrancheAge
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kkPDExG": it references class "App\\Entity\\TrancheAge" but no such service exists.');
    }
}
