<?php

namespace ContainerOiS04YC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TagType' shared autowired service.
     *
     * @return \App\Form\TagType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TagType.php';

        return $container->privates['App\\Form\\TagType'] = new \App\Form\TagType();
    }
}
